name: Ubuntu Compile Check CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - name: Install xmake
        id: install
        shell: bash
        run: |
          wget https://xmake.io/shget.text -O - | bash

      - name: Build ubuntu
        id: build
        shell: bash
        run: |
          xmake
