name: Ubuntu Compile Check CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install gcc and g++
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++

      - name: Install xmake
        run: |
          wget https://xmake.io/shget.text -O - | bash

      - name: Build
        run: |
          pwd
          ls -al
          xmake
